### ISSUE TITLE
Move to Selective org

### ISSUE THREAD

**Issue by peter279k** [selective-php/validation#2]
@odan, do you have the plan to move this package to this org?

**Comment by odan** [comment]
At the moment I'm not planning to move this package. It's more or less "feature complete". Do you have ideas for more?

**Comment by peter279k** [comment]
Hi @odan, I agree with that, but I think this package still has the small changes (I think) need to be concerned.

These changes are as follows:

- Complete the return type hints.
Some changes are not completed, and it should be considered.
- Add the latest stable PHP version (such as `php-7.3`) during Travis CI build.

Excluding these small changes I mention, I think it's the "feature complete" :).

**Comment by odan** [comment]
Done
