### ISSUE TITLE
In which layer would you recommend placing the validation logic?

### ISSUE THREAD

**Issue by notflip** [selective-php/validation#6]
Thank you, first of all for this package!

I'm wondering in which layer you would advice to place this validation logic,
Would you place it in the Action class? (When using ADR), or closer to the Domain?

**Comment by odan** [comment]
All the validation is part of the domain and should be done in the domain layer e.g. in a service class or sometimes in a  more specific validation class if the validation is very complex.

**Comment by notflip** [comment]
Thanks for the fast response!
